package com.hyt.beans;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.photo_a
     *
     * @mbggenerated
     */
    private String photoA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.photo_b
     *
     * @mbggenerated
     */
    private String photoB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.photo_c
     *
     * @mbggenerated
     */
    private String photoC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.st
     *
     * @mbggenerated
     */
    private String st;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.author
     *
     * @return the value of news.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.author
     *
     * @param author the value for news.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.photo_a
     *
     * @return the value of news.photo_a
     *
     * @mbggenerated
     */
    public String getPhotoA() {
        return photoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.photo_a
     *
     * @param photoA the value for news.photo_a
     *
     * @mbggenerated
     */
    public void setPhotoA(String photoA) {
        this.photoA = photoA == null ? null : photoA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.photo_b
     *
     * @return the value of news.photo_b
     *
     * @mbggenerated
     */
    public String getPhotoB() {
        return photoB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.photo_b
     *
     * @param photoB the value for news.photo_b
     *
     * @mbggenerated
     */
    public void setPhotoB(String photoB) {
        this.photoB = photoB == null ? null : photoB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.photo_c
     *
     * @return the value of news.photo_c
     *
     * @mbggenerated
     */
    public String getPhotoC() {
        return photoC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.photo_c
     *
     * @param photoC the value for news.photo_c
     *
     * @mbggenerated
     */
    public void setPhotoC(String photoC) {
        this.photoC = photoC == null ? null : photoC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.st
     *
     * @return the value of news.st
     *
     * @mbggenerated
     */
    public String getSt() {
        return st;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.st
     *
     * @param st the value for news.st
     *
     * @mbggenerated
     */
    public void setSt(String st) {
        this.st = st == null ? null : st.trim();
    }
}